; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	# adafruit/Adafruit SHT4x Library @ ^1.0.4  // Disabled: SHT40 breakout conflicts with PCB pull-ups. Re-enable when new PCB is ready.
	adafruit/Adafruit NeoPixel @ ^1.12.0
	maarten-pennings/ENS210@^1.0.0
